### ISSUE TITLE
Exhumed - 0.7.3_alpha-250- map 20 energy tower sprites

### ISSUE THREAD

**Issue by Axldomi** [coelckers/Raze#159]
The previous bug where the game would partially freeze at the beginning of level 20 has been fixed  (#152).

But the Energy tower shows some weird sprite behaviour. See screenshots below.

![Exhumed_0000](https://user-images.githubusercontent.com/71838912/98436553-8f0fbf80-20dc-11eb-967a-76ce64b34b69.png)

![Exhumed_0001](https://user-images.githubusercontent.com/71838912/98436559-9636cd80-20dc-11eb-8fac-b3b16745bf87.png)

**Comment by sinisterseed** [comment]
Indeed, now this one is pretty old honestly.

It was present in the old base as well, but not addressed, yet.

**Comment by mjr4077au** [comment]
Made the tower work fine. The issues with the spark are the same issues with the plasma in the menu. If they're not drawn over a black background, you see black behind the spark instead of an alpha channel.

Might need to defer to Graf on that one but at least a long-standing issue from 11b8017752adee1a62b0c8e96297089e9665c9d7 has been resolved.

**Comment by coelckers** [comment]
How about a savegame? I have no desire to play through this labyrinthine level just to test a graphical effect.

**Comment by coelckers** [comment]
Should be fixed, btw.

**Comment by mjr4077au** [comment]
Cool that it should be fixed, but the issue is right at the start of LEV20 so warping there is enough. Just have to hit the first switch and shoot out the energy tower 😊

**Comment by sinisterseed** [comment]
Yes indeed.

You can't miss it 😉 .

**Comment by coelckers** [comment]
It's fixed now.

**Comment by arrowgent** [comment]
warp: map lev20
give all

still crashed v0.7.3alpha (linux)
i can recompile master to verify this fix
