### ISSUE TITLE
[BUG, Blood] DeleteSprite/RemoveSpriteStat assert

### ISSUE THREAD

**Issue by Talon1024** [coelckers/Raze#537]
### Raze version

Git 9e58d25ccb99410396d6c1cb3a84c33ac3e6862d

### What Operating System are you using?

Linux x86_64

### Which game are you running with Raze?

Blood

### If Other OS, please describe

Kubuntu 20.04

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

An assertion failure can happen when the game tries to remove sprites(?).

Saved game (`Blood.Blood`): [save0001.zip](https://github.com/coelckers/Raze/files/7102539/save0001.zip)

### Steps to reproduce the behaviour.

1. Load the saved game
2. Just wait for a few seconds
3. Assertion failure (see log)

### Your configuration

```ini
I am using the new renderer
```

### Provide a Log

    raze: ../source/games/blood/src/db.cpp:141: void Blood::RemoveSpriteStat(int): Assertion `nSprite >= 0 && nSprite < kMaxSprites' failed.

**Comment by coelckers** [comment]
What's up? Can you please tell us why you closed it?

**Comment by Talon1024** [comment]
I thought this bug would have been fixed in one of the recent commits.

**Comment by Talon1024** [comment]
I think I found a way to consistently reproduce the assert: Use the Flare Pistol's alternative fire. The assert will happen 5-6 seconds later.

**Comment by coelckers** [comment]
It tries to double-delete an actor in the event queue. Unfortunately that's too late to find out why it got added redundantly to the queue.

**Comment by coelckers** [comment]
I think I have found the cause for this. Some code called the wrong function to delete this thing from the list.

**Comment by Talon1024** [comment]
This assertion failure is happening again...

**Comment by coelckers** [comment]
The bug is already in the savegame, it also asserts on versions much older than my refactoring. The bug causing this was fixed in 3c3da13d3f8ae18cebd123a126dd77349cc8fdf4 if I am not mistaken. That commit was done on Sep 12th.

**Comment by Talon1024** [comment]
It's still happening, even if I start a new game, on a build from 9433e9bdb14bdbe42be28e06404691e392c6edef. Just pick up the flare pistol and use its alternate fire, and wait about 5 seconds for the assertion failure to happen.

**Comment by sinisterseed** [comment]
Can't replicate on a fresh build on Windows either.

At this rate it kinda sounds like something Linux specific honestly.

**Comment by Talon1024** [comment]
Or maybe you're not using a Debug build? Release builds don't have these asserts in them.

**Comment by sinisterseed** [comment]
Good point, didn't know it was Debug specific, I was using a RelWithDebInfo build to test out. I'll see if a Debug crashes when using the Flare altfire.

**Comment by sinisterseed** [comment]
Yeah, confirmed it crashes on Windows too, with a Debug build. Flare altfire + wall = assertion failure.

> db.cpp Line: 225.
> Expression: sprite[nSprite].statnum >= 0 && sprite[nSprite].statnum <kMaxStatus

**Comment by coelckers** [comment]
Does it happen with the develop branch as well? I tried endlessly and experienced no problems with this. The mentioned commit is from before merging in all my refactoring stuff.

**Comment by sinisterseed** [comment]
Can't reproduce it anymore either, so whatever it was, it must've been fixed with the refactor.

So case solved, for the time being.
