### ISSUE TITLE
[BUG] [macOS] issue #606 was not fixed correctly - Game folders in Application Support

### ISSUE THREAD

**Issue by shinra-electric** [coelckers/Raze#669]
### Raze version

1.4.1

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Mac OS

### Relevant hardware info

M1

### Have you checked that no other similar issue already exists?

- [ ] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

This is the same issue as #606 which was supposed to be fixed by [910c0e6](https://github.com/coelckers/Raze/commit/910c0e61cabe4780e86b5f64d5f7f92f268f8dc7), however it was not. 

Raze should search for game files in `~/Library/Application Support/Raze/ `

The above mentioned pull request was supposed to add  `~/Library/Application Support/Raze/ *` with a wild star so that Raze would search all folders in there. 

However, the pull request made 2 mistakes: 
a) It added the shared library, not the user library
b) It added an extra Raze folder, so it looks in `Library/Application Support/Raze/Raze/*` 

Here is the default [GameSearch.Directories] section of a fresh raze.ini file: 

`[GameSearch.Directories]`
`Path=.`
`Path=./*`
`Path=/Users/xianmo/Documents/Raze/*`
`Path=/Users/xianmo/Library/Application Support/Raze/EDuke32`
`Path=/Users/xianmo/Library/Application Support/Raze/JFDuke32`
`Path=/Users/xianmo/Library/Application Support/Raze/NBlood`
`Path=$PROGDIR`
`Path=$PROGDIR/*`
`Path=/Library/Application Support/Raze/EDuke32`
`Path=/Library/Application Support/Raze/JFDuke32`
`Path=/Library/Application Support/Raze/NBlood`
`Path=/Library/Application Support/Raze/JFSW`
`Path=/Library/Application Support/Raze/VoidSW`
`Path=/Library/Application Support/Raze/Raze/*` <--Should be user library, and only have one Raze directory
`Path=$STEAM`

Manually adding `Path=/Users/[User-name-here]/Library/Application Support/Raze/*` will allow raze to find the game files.

**Comment by coelckers** [comment]
fixed in 6354c1889d4b5a8b261cc5c52a1a709bb0326b31

**Comment by shinra-electric** [comment]
That PR did not fix the issue

**Comment by shinra-electric** [comment]
I deleted an incorrect comment saying this PR did not fix the issue. Stupidly I had not realised the PR has not been included in a release yet. 

I am trying to build myself to test, although I'm getting build errors.
